config/routes.rb
Rails.application.routes.draw do
  resources :near_stations
  resources :properties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/near_station.rb
class NearStation < ApplicationRecord
  belongs_to :property, optional: true
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :near_stations, dependent: :destroy
  accepts_nested_attributes_for :near_stations, reject_if: :reject_posts, allow_destroy: true
end

def reject_posts(attributes)
  #attributes['line_name'].blank? && attributes['station_name'].blank? && attributes['minutes'].blank?
  exists = attributes[:id].present?
  empty = attributes[:line_name].blank? && attributes[:station_name].blank? && attributes[:minutes].blank?
  attributes.merge!(_destroy: 1) if exists && empty
  !exists && empty
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @near_stations = @property.near_stations
  end

  # GET /properties/new
  def new
    @property = Property.new
    @property.near_stations.build
  end

  # GET /properties/1/edit
  def edit
    @near_stations = @property.near_stations
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    if @property.save
      redirect_to property_path(@property), notice: 'Property was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    if @property.update(property_params)
      redirect_to @property, notice: 'Property was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    redirect_to properties_url, notice: 'Property was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(
          :name,
          :price,
          :address,
          :age,
          :remark,
          near_stations_attributes: [:line_name,
                        :station_name,
                        :minutes,
                        :id]
                                        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/near_stations_helper.rb
module NearStationsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MofMof</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/edit.html.erb
<h1>物件編集</h1>

<%= form_with(model: @property, local: true) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% @property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :物件名 %>
    <p><%= f.text_field :name %></p>
  </div>
  <div class="field">
    <%= f.label :賃料 %>
    <p><%= f.text_field :price %>円</p>
  </div>
  <div class="field">
    <%= f.label :住所 %>
    <p><%= f.text_field :address %></p>
  </div>
  <div class="field">
    <%= f.label :築年数 %>
    <p><%= f.text_field :age %>年</p>
  </div>
  <div class="field">
    <p><%= f.label :備考 %></p>
    <p><%= f.text_area :remark %>
  </div>


  <hr>

  <% i = 1 %>
  <%= f.fields_for :near_stations, @near_stations do |p| %>
    <p>最寄駅<%= i %></p>
    <div class="field">
      <%= p.label :路線名 %>
      <p><%= p.text_field :line_name %></p>
    </div>
    <div class="field">
      <%= p.label :駅名 %>
      <p><%= p.text_field :station_name %></p>
    </div>
    <div class="field">
      <%= p.label :徒歩分数 %>
      <p><%= p.text_field :minutes %>分</p>
    </div>
    <% i += 1 %>
  <% end %>

  <%= f.fields_for :near_stations, @property.near_stations.build do |p| %>
    <p>最寄駅<%= @near_stations.count + 1 %></p>
    <div class="field">
      <%= p.label :路線名 %>
      <p><%= p.text_field :line_name %></p>
    </div>
    <div class="field">
      <%= p.label :駅名 %>
      <p><%= p.text_field :station_name %></p>
    </div>
    <div class="field">
      <%= p.label :徒歩分数 %>
      <p><%= p.text_field :minutes %>分</p>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit "更新する" %>
  </div>
<% end %>

<%= link_to '詳細', @property %> |
<%= link_to '戻る', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>物件一覧</h1>

<table>
  <thead>
    <tr>
      <th>物件名</th>
      <th>賃料</th>
      <th>住所</th>
      <th>築年数</th>
      <th>備考</th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.price %></td>
        <td><%= property.address %></td>
        <td><%= property.age %></td>
        <td><%= property.remark %></td>
        <td><%= link_to '詳細', property %></td>
        <td><%= link_to '編集', edit_property_path(property) %></td>
        <td><%= link_to '削除', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '物件を登録する', new_property_path %>

app/views/properties/new.html.erb
<h1>物件登録</h1>

<%= form_with(model: @property, local: true) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :物件名 %>
    <p><%= f.text_field :name %></p>
  </div>
  <div class="field">
    <%= f.label :賃料 %>
    <p><%= f.text_field :price %>円</p>
  </div>
  <div class="field">
    <%= f.label :住所 %>
    <p><%= f.text_field :address %></p>
  </div>
  <div class="field">
    <%= f.label :築年数 %>
    <p><%= f.text_field :age %>年</p>
  </div>
  <div class="field">
    <p><%= f.label :備考 %></p>
    <p><%= f.text_area :remark %>
  </div>

  <hr>

  <% i = 1 %>
  <% 2.times do %>
    <%= f.fields_for :near_stations, @property.near_stations.build do |p| %>
      <h2>最寄駅<%= i %></h2>
      <div class="field">
        <%= p.label :路線名 %>
        <p><%= p.text_field :line_name %></p>
      </div>
      <div class="field">
        <%= p.label :駅名 %>
        <p><%= p.text_field :station_name %></p>
      </div>
      <div class="field">
        <%= p.label :徒歩分数 %>
        <p><%= p.text_field :minutes %>分</p>
      </div>
      <% i += 1 %>
    <% end %>
  <% end %>
  <div class="actions">
    <%= f.submit "登録する" %>
  </div>

<% end %>


<%= link_to '戻る', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>物件名:<%= @property.name %></p>
<p>賃料:<%= @property.price %>円</p>
<p>住所:<%= @property.address %></p>
<p>築年数 <%= @property.age %>年</p>
<p>備考 <%= @property.remark %></p>

<hr>

<% i = 1 %>
<% @near_stations.each do |nearest_station| %>
  <h2>最寄駅<%= i %></h2>
  <p>路線名:<%= nearest_station.line_name %></p>
  <p>駅名:<%= nearest_station.station_name %></p>
  <p>徒歩分数:<%= nearest_station.minutes %>分</p>
  <% i += 1 %>
<% end %>

<%= link_to '編集', edit_property_path(@property) %> |
<%= link_to '戻る', properties_path %>